MTLS Authetication changes
Mastercard/crossborder-services-reference-app-oauth2 pull request #8
Opened 2022-05-11 12:44 UTC by sonawalesonali

2022-05-11 12:50 UTC, avantipande1 approved these changes

2022-05-12 09:47 UTC, chaitanyasapre requested changes

2022-05-12 09:47 UTC, chaitanyasapre commented on src/main/resources/mastercard-api.properties
> +9
why have you added 9 here?

2022-05-13 06:20 UTC, chaitanyasapre approved these changes
looks good

2022-05-13 06:20 UTC, chaitanyasapre commented on src/main/resources/mastercard-api.properties
> +mastercard.api.environment.sandbox.endPointURL=https://stage.api.xbs.mastercard.eu
remove stage url or replace this with sandbox url

2022-05-13 06:21 UTC, merged